"""
Django settings for zhuartcc project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*(8x#v^ooemwe2y02xx3e^80@^ou24hqs@u$46t6s-wmzvnmz#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.7', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.resource',
    'apps.training',
    'apps.uls',
    'apps.user.apps.UserConfig',
    'apps.views',
    'apps.visit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zhuartcc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'public/../templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zhuartcc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/')
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Email Settings

EMAIL_HOST = 'HOST'

EMAIL_PORT = 587

EMAIL_HOST_USER = 'USERNAME'

EMAIL_HOST_PASSWORD = 'PASSWORD'

EMAIL_USE_TLS = True


# VATUSA Settings

ULS_KEY = {"alg":"HS256","use":"sig","kty":"oct","k":"NotARealULSKey"}

API_KEY = 'NotARealAPIKey'


# Global Settings

RESOURCE_CATEGORIES = ['VRC', 'vSTARS', 'vERAM', 'vATIS', 'SOP', 'LOA', 'MAVP', 'Misc']

ARTCC_BOUNDARY = [[29.750948327823,-102.60824034622],[31.283333,-102.15],[30.983333,-100.55],[31.383333,-99.466667],[31.390278,-97.794444],[31.375,-97.7125],[31.2125,-97.5125],[31.2,-97.2],[31.204167,-96.683333],[31.466667,-95.983333],[31.572222,-94.2],[31.558333,-93.320833],[32.283333,-92.258333],[32.283333,-91.688889],[31.9125,-91.308333],[31.65,-90.345833],[31.630556,-89.85],[31.547222,-88.9],[31.516667,-88.325],[31.520833,-87.816667],[31.280556,-87.4],[30.958333,-87.658333],[30.845833,-87.683333],[30.691667,-87.716667],[30.683333,-87.808333],[30.633333,-87.916667],[30.516667,-87.916667],[30.220833,-88.025],[28.141667,-88],[28.25,-89],[28.25,-94],[27.533333,-95.15],[26,-95.916667],[26,-96],[26,-97],[25.869043172204,-97.388493553493],[26.070726909672,-98.091092340946],[26.292735070613,-98.776190679968],[26.888602790934,-99.340290948019],[27.52051581641,-99.53891568499],[27.780131371739,-99.839971618437],[28.140362112323,-100.08942144531],[28.463148905445,-100.34544024514],[28.848624700819,-100.59064627128],[29.167337408347,-100.7739464609],[29.472992640119,-101.1370071638],[29.694908445859,-101.37963793743],[29.801783018518,-101.51580361791],[29.762829394758,-101.63670953195],[29.782872690139,-101.89233296199],[29.807946723575,-102.17346543777],[29.84718137648,-102.32886411017],[29.766733914596,-102.41464472227],[29.7691780458,-102.50786992176],[29.747103387149,-102.55042371958],[29.765785146193,-102.56709644133],[29.750948327823,-102.60824034622]]

MAP_CENTER = [29.7604, -94.3698]
